### PR TITLE
setup integration tests

### PR DESCRIPTION
**Pull request by iAmNathanJ**
@boomingbrake @BC3209 @catheraaine 

This might break circleci.

### CODE REVIEW

**Comment by iAmNathanJ** [comment]
Uh... ok. I guess not.

**Comment by BC3209** [comment]
Nice!

**Comment by iAmNathanJ** [comment]
I'm an idiot.

**Comment by catheraaine** [comment]
@iAmNathanJ You are doing awesome. 

idiot

**Pull request closed without merging**
