### PR TITLE
:art:Refactor: Restructure Sass Files

### LINKED ISSUE #53: Restructure Sass
- [ ] Refactor file structure for project growth 

(Partial all the things)

### PR DESCRIPTION
**Pull request by catheraaine**
- Add `main.sass` as master import file.
  - Refactor `application.css` to compile only `main.scss`
  - Add Sass partials.
  - Add  `normalize.scss` and very minimal `reset.scss`

closes #53

### CODE REVIEW

**Comment by catheraaine** [comment]
@iAmNathanJ @BC3209 @boomingbrake 

Sassssssy Files! 

sassy gif

**Comment by iAmNathanJ** [comment]
@catheraaine I have a couple question/comments. Why normalize && reset?

Also, I think there should be a variables partial. No?

**Comment by catheraaine** [comment]
@iAmNathanJ Normalize is the MIT base normalize that just makes browsers behave predictably. I am not sure if it is a thing at SB. 

The reset is super limited - only "fixes" a few things. Lists + Links usually. 

Variables file could be good, I have them in global now.

**Comment by iAmNathanJ** [comment]
@catheraaine Right. Sorry what i should have asked was why both? I like the minimal reset. The normalize seems like extra heft. 😄  Anyone else have thoughts? @boomingbrake @BC3209

**Comment by catheraaine** [comment]
Website Test for this PR

**Comment by iAmNathanJ** [comment]
@catheraaine Awesome! Those are changes are beautiful. Will merge now.

**Pull request merged**
