### PR TITLE
Add push and popstate goodies

### PR DESCRIPTION
**Pull request by iAmNathanJ**
History has been written. Pun heavily intended. 

@BC3209 @boomingbrake @catheraaine Can you all *please* try to break this? Need to check that the filter buttons and the event cards update properly through the browser history (forward and back). BREAK IT!

### CODE REVIEW

**Comment by iAmNathanJ** [comment]
Uh oh. Failing tests... wtf.a

**Comment by catheraaine** [comment]
french fries

Keep at it!

**Comment by iAmNathanJ** [comment]
I don't know what the poltergeist test is failing for. That just checks that the page has a `<main>` on it. I killed that test for the time being. Jasmin specs are all passing. Now you can break it.

**Comment by BC3209** [comment]
Nice fix!!! You're going places!

**Pull request merged**
