### PR TITLE
Feat: About / Submit Links with Hover State

### PR DESCRIPTION
**Pull request by catheraaine**

### CODE REVIEW

**Comment by catheraaine** [comment]
@iAmNathanJ @BC3209 @boomingbrake 

Just some polish on the about / submit links

**Comment by iAmNathanJ** [comment]
@catheraaine I hate to nitpick on this one, but I'm not sure about the double line. It changes layout on hover, which is not really ok. Wanna try another variation or two?

**Comment by catheraaine** [comment]
I'm just not sure how to make an accessible link (with visual, not color hover effect).

**Comment by catheraaine** [comment]
@iAmNathanJ updated.

**Comment by iAmNathanJ** [comment]
@catheraaine Cool. I think this is better. Thanks!

**Pull request merged**
