### PR TITLE
:bug: Fix: Move <div> outside <ul> on Event Card

### LINKED ISSUE #197: Event Card - <div> inside <li> elements
🐱 🐛

### PR DESCRIPTION
**Pull request by catheraaine**
closes #197

### CODE REVIEW

**Comment by catheraaine** [comment]
@iAmNathanJ @BC3209 @boomingbrake

**Comment by iAmNathanJ** [comment]
@catheraaine Reviewing this now...

**Comment by iAmNathanJ** [comment]
Ok, this looks good. Do you want to tackle a couple more small issues on this branch before we merge? Could be quick. Either way, let me know.

Issues are:
1. id="icon-window" is being used on every svg building icon. ID's should be unique, so maybe we can just remove it?
2. Shareable link label should be a `<label for="shareable-link-[event#]">`. Then each link text field should have `id="shareable-link-[event#]" `

Let me know what you want to do. 😄

**Comment by catheraaine** [comment]
@iAmNathanJ updated!

**Comment by iAmNathanJ** [comment]
@catheraaine Awesome work! 😄

**Pull request merged**
