### PR TITLE
Config: Update production config

### PR DESCRIPTION
**Pull request by iAmNathanJ**
Redirect logger to STDOUT. This should allow us to see app errors with
`heroku logs`... I think.

@catheraaine @boomingbrake @BC3209

### CODE REVIEW

**Comment by iAmNathanJ** [comment]
Don't merge this yet. I'm going to force an error on this build and confirm the logging.

**Comment by BC3209** [comment]
Heroku logs in console doesn't show it?
I see them

**Comment by iAmNathanJ** [comment]
@BC3209 I had to commit another change bc I broke the ci tests, so the app didn't build. Now it works a treat. Do `heroku logs --tail --app lamp-post-pr-40` Note: pass the app name for review apps. Follow that log back and you should see the error I forced with code output from the view, including line numbers. Huzzah. This pleases me.

**Comment by iAmNathanJ** [comment]
@BC3209 Don't merge yet. I'm gonna document this.

**Comment by iAmNathanJ** [comment]
@BC3209 I think this is all good. Wanna take a look. 👀

**Comment by BC3209** [comment]
I see the error on the logs. Everything looks good to me. Good to merge?

**Comment by BC3209** [comment]
Merged!!!

**Pull request merged**
